---
kind: pipeline
name: drone-test

steps: 
  - name: step 1 
    image: alpine
    commands:
            - echo "hello world"
steps: 
  - name: step 2 (sleep) 
    image: alpine
    commands:
            - sleep 10
            - echo "hello world"
steps: 
  - name: step 3
    image: alpine
    commands:
            - echo "hello world"
steps: 
  - name: step 4 
    image: alpine
    commands:
            - echo "hello world"
